export const mockDockingJobs = [
  {
    job_id: "job_001_aspirin_cox2",
    status: "completed" as const,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    protein_name: "COX-2 Enzyme",
    ligand_name: "Aspirin",
    disease_target: "Inflammation & Pain",
  },
  {
    job_id: "job_002_ibuprofen_cox1",
    status: "completed" as const,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    protein_name: "COX-1 Enzyme",
    ligand_name: "Ibuprofen",
    disease_target: "Inflammation & Pain",
  },
  {
    job_id: "job_003_remdesivir_rdrp",
    status: "running" as const,
    created_at: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    protein_name: "RNA-dependent RNA polymerase",
    ligand_name: "Remdesivir",
    disease_target: "COVID-19",
    progress: 65,
  },
  {
    job_id: "job_004_penicillin_pbp",
    status: "queued" as const,
    created_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    protein_name: "Penicillin-binding protein",
    ligand_name: "Penicillin G",
    disease_target: "Bacterial infection",
  },
  {
    job_id: "job_005_statin_hmgr",
    status: "failed" as const,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    protein_name: "HMG-CoA reductase",
    ligand_name: "Atorvastatin",
    disease_target: "Hypercholesterolemia",
    error: "Invalid protein structure format",
  },
  {
    job_id: "job_006_oseltamivir_neuraminidase",
    status: "completed" as const,
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    protein_name: "Influenza Neuraminidase",
    ligand_name: "Oseltamivir (Tamiflu)",
    disease_target: "Influenza",
  },
  {
    job_id: "job_007_gefitinib_egfr",
    status: "completed" as const,
    created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    protein_name: "EGFR Kinase",
    ligand_name: "Gefitinib",
    disease_target: "Non-Small Cell Lung Cancer",
  },
  {
    job_id: "job_008_lisinopril_ace",
    status: "running" as const,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    protein_name: "Angiotensin-Converting Enzyme (ACE)",
    ligand_name: "Lisinopril",
    disease_target: "Hypertension",
    progress: 78,
  },
  {
    job_id: "job_009_metformin_ampk",
    status: "predicting_structure" as const,
    created_at: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    protein_name: "AMP-Activated Protein Kinase",
    ligand_name: "Metformin",
    disease_target: "Type 2 Diabetes",
    progress: 45,
  },
  {
    job_id: "job_010_semaglutide_glp1r",
    status: "structure_predicted" as const,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    protein_name: "GLP-1 Receptor",
    ligand_name: "Semaglutide",
    disease_target: "Type 2 Diabetes & Obesity",
    progress: 55,
    plddt_score: 87.3,
  },
]

const EXAMPLE_PDB = `COMPND    UNNAMED
AUTHOR    GENERATED BY OPEN BABEL 2.3.2
ATOM      1  N   ALA A   1       0.000   0.000   0.000  1.00  0.00           N  
ATOM      2  CA  ALA A   1       1.456   0.000   0.000  1.00  0.00           C  
ATOM      3  C   ALA A   1       1.930   0.000   1.463  1.00  0.00           C  
ATOM      4  O   ALA A   1       1.160   0.000   2.421  1.00  0.00           O  
ATOM      5  HN  ALA A   1      -0.495   0.091   0.883  1.00  0.00           H  
ATOM      6  HA  ALA A   1       1.799  -0.926  -0.476  1.00  0.00           H  
ATOM      7  CB  ALA A   1       2.010   1.208  -0.746  1.00  0.00           C  
ATOM      8  1HB ALA A   1       1.657   1.230  -1.782  1.00  0.00           H  
ATOM      9  2HB ALA A   1       1.695   2.143  -0.268  1.00  0.00           H  
ATOM     10  3HB ALA A   1       3.104   1.197  -0.763  1.00  0.00           H  
ATOM     11  HN  ALA A   1      -0.508   0.077  -0.877  1.00  0.00           H  
ATOM     12  N   ALA A   2       3.241  -0.000   1.742  1.00  0.00           N  
ATOM     13  CA  ALA A   2       3.690   0.000   3.127  1.00  0.00           C  
ATOM     14  C   ALA A   2       5.228   0.000   3.127  1.00  0.00           C  
ATOM     15  O   ALA A   2       5.902  -0.000   2.098  1.00  0.00           O  
ATOM     16  HN  ALA A   2       3.928  -0.091   0.999  1.00  0.00           H  
ATOM     17  HA  ALA A   2       3.343   0.926   3.600  1.00  0.00           H  
ATOM     18  CB  ALA A   2       3.151  -1.208   3.884  1.00  0.00           C  
ATOM     19  1HB ALA A   2       2.057  -1.230   3.869  1.00  0.00           H  
ATOM     20  2HB ALA A   2       3.508  -2.143   3.438  1.00  0.00           H  
ATOM     21  3HB ALA A   2       3.472  -1.197   4.931  1.00  0.00           H  
ATOM     22  N   ALA A   3       5.898   0.000   4.287  1.00  0.00           N  
ATOM     23  CA  ALA A   3       7.353   0.000   4.287  1.00  0.00           C  
ATOM     24  C   ALA A   3       7.828   0.000   5.750  1.00  0.00           C  
ATOM     25  O   ALA A   3       7.058   0.001   6.709  1.00  0.00           O  
ATOM     26  HN  ALA A   3       5.403   0.092   5.170  1.00  0.00           H  
ATOM     27  HA  ALA A   3       7.696  -0.926   3.811  1.00  0.00           H  
ATOM     28  CB  ALA A   3       7.907   1.208   3.541  1.00  0.00           C  
ATOM     29  1HB ALA A   3       7.555   1.230   2.505  1.00  0.00           H  
ATOM     30  2HB ALA A   3       7.593   2.143   4.018  1.00  0.00           H  
ATOM     31  3HB ALA A   3       9.002   1.197   3.524  1.00  0.00           H  
ATOM     32  N   ALA A   4       9.138   0.000   6.029  1.00  0.00           N  
ATOM     33  CA  ALA A   4       9.587   0.001   7.414  1.00  0.00           C  
ATOM     34  C   ALA A   4      11.125   0.000   7.414  1.00  0.00           C  
ATOM     35  O   ALA A   4      11.799  -0.000   6.386  1.00  0.00           O  
ATOM     36  HN  ALA A   4       9.825  -0.092   5.286  1.00  0.00           H  
ATOM     37  HA  ALA A   4       9.240   0.927   7.887  1.00  0.00           H  
ATOM     38  CB  ALA A   4       9.048  -1.207   8.171  1.00  0.00           C  
ATOM     39  1HB ALA A   4       7.954  -1.229   8.156  1.00  0.00           H  
ATOM     40  2HB ALA A   4       9.405  -2.142   7.726  1.00  0.00           H  
ATOM     41  3HB ALA A   4       9.370  -1.196   9.218  1.00  0.00           H  
ATOM     42  N   PHE A   5      11.795   0.001   8.574  1.00  0.00           N  
ATOM     43  CA  PHE A   5      13.257   0.000   8.574  1.00  0.00           C  
ATOM     44  C   PHE A   5      13.697   0.001  10.048  1.00  0.00           C  
ATOM     45  O   PHE A   5      12.900   0.002  10.985  1.00  0.00           O  
ATOM     46  CB  PHE A   5      13.815   1.225   7.831  1.00  0.00           C  
ATOM     47  CG  PHE A   5      15.237   1.036   7.355  1.00  0.00           C  
ATOM     48  CD2 PHE A   5      16.308   1.641   8.027  1.00  0.00           C  
ATOM     49  CE2 PHE A   5      17.618   1.438   7.592  1.00  0.00           C  
ATOM     50  CZ  PHE A   5      17.869   0.639   6.477  1.00  0.00           C  
ATOM     51  CE1 PHE A   5      16.810   0.041   5.797  1.00  0.00           C  
ATOM     52  CD1 PHE A   5      15.500   0.236   6.234  1.00  0.00           C  
ATOM     53  H   PHE A   5      11.328   0.281   9.433  1.00  0.00           H  
ATOM     54  HA  PHE A   5      13.585  -0.939   8.112  1.00  0.00           H  
ATOM     55  HB1 PHE A   5      13.752   2.118   8.467  1.00  0.00           H  
ATOM     56  HB2 PHE A   5      13.201   1.454   6.950  1.00  0.00           H  
ATOM     57  HD2 PHE A   5      16.130   2.272   8.895  1.00  0.00           H  
ATOM     58  HE2 PHE A   5      18.445   1.910   8.117  1.00  0.00           H  
ATOM     59  HZ  PHE A   5      18.889   0.489   6.133  1.00  0.00           H  
ATOM     60  HE1 PHE A   5      17.003  -0.573   4.921  1.00  0.00           H  
ATOM     61  HD1 PHE A   5      14.680  -0.233   5.690  1.00  0.00           H  
ATOM     62  N   ALA A   6      15.001   0.000  10.358  1.00  0.00           N  
ATOM     63  CA  ALA A   6      15.418   0.001  11.752  1.00  0.00           C  
ATOM     64  C   ALA A   6      16.955   0.001  11.788  1.00  0.00           C  
ATOM     65  O   ALA A   6      17.653  -0.000  10.776  1.00  0.00           O  
ATOM     66  HN  ALA A   6      15.705  -0.092   9.631  1.00  0.00           H  
ATOM     67  HA  ALA A   6      15.060   0.927  12.217  1.00  0.00           H  
ATOM     68  CB  ALA A   6      14.861  -1.206  12.497  1.00  0.00           C  
ATOM     69  1HB ALA A   6      13.767  -1.228  12.457  1.00  0.00           H  
ATOM     70  2HB ALA A   6      15.228  -2.142  12.060  1.00  0.00           H  
ATOM     71  3HB ALA A   6      15.158  -1.195  13.551  1.00  0.00           H  
ATOM     72  N   ALA A   7      17.598   0.001  12.964  1.00  0.00           N  
ATOM     73  CA  ALA A   7      19.053   0.000  12.998  1.00  0.00           C  
ATOM     74  C   ALA A   7      19.494   0.001  14.471  1.00  0.00           C  
ATOM     75  O   ALA A   7      18.701   0.002  15.412  1.00  0.00           O  
ATOM     76  HN  ALA A   7      17.083   0.093  13.835  1.00  0.00           H  
ATOM     77  HA  ALA A   7      19.407  -0.926  12.530  1.00  0.00           H  
ATOM     78  CB  ALA A   7      19.625   1.208  12.264  1.00  0.00           C  
ATOM     79  1HB ALA A   7      19.297   1.229  11.219  1.00  0.00           H  
ATOM     80  2HB ALA A   7      19.300   2.143  12.733  1.00  0.00           H  
ATOM     81  3HB ALA A   7      20.720   1.196  12.272  1.00  0.00           H  
ATOM     82  N   ALA A   8      20.797   0.001  14.781  1.00  0.00           N  
ATOM     83  CA  ALA A   8      21.214   0.002  16.175  1.00  0.00           C  
ATOM     84  C   ALA A   8      22.751   0.001  16.211  1.00  0.00           C  
ATOM     85  O   ALA A   8      23.449  -0.001  15.199  1.00  0.00           O  
ATOM     86  HN  ALA A   8      21.502  -0.092  14.054  1.00  0.00           H  
ATOM     87  HA  ALA A   8      20.857   0.928  16.640  1.00  0.00           H  
ATOM     88  CB  ALA A   8      20.657  -1.206  16.921  1.00  0.00           C  
ATOM     89  1HB ALA A   8      19.563  -1.227  16.880  1.00  0.00           H  
ATOM     90  2HB ALA A   8      21.024  -2.141  16.484  1.00  0.00           H  
ATOM     91  3HB ALA A   8      20.954  -1.194  17.975  1.00  0.00           H  
ATOM     92  N   ALA A   9      23.394   0.002  17.387  1.00  0.00           N  
ATOM     93  CA  ALA A   9      24.850   0.000  17.421  1.00  0.00           C  
ATOM     94  C   ALA A   9      25.290   0.002  18.894  1.00  0.00           C  
ATOM     95  O   ALA A   9      24.498   0.003  19.835  1.00  0.00           O  
ATOM     96  HN  ALA A   9      22.879   0.094  18.258  1.00  0.00           H  
ATOM     97  HA  ALA A   9      25.203  -0.926  16.953  1.00  0.00           H  
ATOM     98  CB  ALA A   9      25.421   1.208  16.687  1.00  0.00           C  
ATOM     99  1HB ALA A   9      25.093   1.229  15.642  1.00  0.00           H  
ATOM    100  2HB ALA A   9      25.097   2.143  17.156  1.00  0.00           H  
ATOM    101  3HB ALA A   9      26.517   1.196  16.695  1.00  0.00           H  
ATOM    102  OXT ALA A   9      26.620   0.001  19.131  1.00  0.00           O  
ATOM    103  HO  ALA A   9      27.305  -0.000  18.317  1.00  0.00           H  
CONECT    1   11    2    5                                            
CONECT    2    1    3    6    7                                       
CONECT    3    2    4   12                                            
CONECT    4    3                                                      
CONECT    5    1                                                      
CONECT    6    2                                                      
CONECT    7    2    8    9   10                                       
CONECT    8    7                                                      
CONECT    9    7                                                      
CONECT   10    7                                                      
CONECT   11    1                                                      
CONECT   12    3   13   16                                            
CONECT   13   12   14   17   18                                       
CONECT   14   13   15   22                                            
CONECT   15   14                                                      
CONECT   16   12                                                      
CONECT   17   13                                                      
CONECT   18   13   19   20   21                                       
CONECT   19   18                                                      
CONECT   20   18                                                      
CONECT   21   18                                                      
CONECT   22   14   23   26                                            
CONECT   23   22   24   27   28                                       
CONECT   24   23   25   32                                            
CONECT   25   24                                                      
CONECT   26   22                                                      
CONECT   27   23                                                      
CONECT   28   23   29   30   31                                       
CONECT   29   28                                                      
CONECT   30   28                                                      
CONECT   31   28                                                      
CONECT   32   24   33   36                                            
CONECT   33   32   34   37   38                                       
CONECT   34   33   35   42                                            
CONECT   35   34                                                      
CONECT   36   32                                                      
CONECT   37   33                                                      
CONECT   38   33   39   40   41                                       
CONECT   39   38                                                      
CONECT   40   38                                                      
CONECT   41   38                                                      
CONECT   42   34   43   53                                            
CONECT   43   42   44   46   54                                       
CONECT   44   43   45   62                                            
CONECT   45   44                                                      
CONECT   46   43   47   56   55                                       
CONECT   47   46   48   52                                            
CONECT   48   47   49   57                                            
CONECT   49   48   50   58                                            
CONECT   50   49   51   59                                            
CONECT   51   50   52   60                                            
CONECT   52   47   51   61                                            
CONECT   53   42                                                      
CONECT   54   43                                                      
CONECT   55   46                                                      
CONECT   56   46                                                      
CONECT   57   48                                                      
CONECT   58   49                                                      
CONECT   59   50                                                      
CONECT   60   51                                                      
CONECT   61   52                                                      
CONECT   62   44   63   66                                            
CONECT   63   62   64   67   68                                       
CONECT   64   63   65   72                                            
CONECT   65   64                                                      
CONECT   66   62                                                      
CONECT   67   63                                                      
CONECT   68   63   69   70   71                                       
CONECT   69   68                                                      
CONECT   70   68                                                      
CONECT   71   68                                                      
CONECT   72   64   73   76                                            
CONECT   73   72   74   77   78                                       
CONECT   74   73   75   82                                            
CONECT   75   74                                                      
CONECT   76   72                                                      
CONECT   77   73                                                      
CONECT   78   73   79   80   81                                       
CONECT   79   78                                                      
CONECT   80   78                                                      
CONECT   81   78                                                      
CONECT   82   74   83   86                                            
CONECT   83   82   84   87   88                                       
CONECT   84   83   85   92                                            
CONECT   85   84                                                      
CONECT   86   82                                                      
CONECT   87   83                                                      
CONECT   88   83   89   90   91                                       
CONECT   89   88                                                      
CONECT   90   88                                                      
CONECT   91   88                                                      
CONECT   92   84   93   96                                            
CONECT   93   92   94   97   98                                       
CONECT   94   93   95  102                                            
CONECT   95   94                                                      
CONECT   96   92                                                      
CONECT   97   93                                                      
CONECT   98   93   99  100  101                                       
CONECT   99   98                                                      
CONECT  100   98                                                      
CONECT  101   98                                                      
CONECT  102   94  103                                                 
CONECT  103  102                                                      
MASTER        0    0    0    0    0    0    0    0  103    0  103    0
END`

export const mockDockingResults = {
  job_001_aspirin_cox2: {
    job_id: "job_001_aspirin_cox2",
    protein_name: "COX-2 Enzyme",
    ligand_name: "Aspirin",
    protein_structure: EXAMPLE_PDB,
    ligand_structure: EXAMPLE_PDB,
    best_pose: {
      pose_id: 0,
      score: -8.7,
      binding_energy: -8.7,
      rmsd: 0.0,
      cluster_id: 1,
      pose_file: EXAMPLE_PDB,
      interactions: { h_bonds: 3, hydrophobic: 4, salt_bridges: 1 },
    },
    poses: [
      { pose_id: 0, score: -8.7, binding_energy: -8.7, rmsd: 0.0, cluster_id: 1, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 3, hydrophobic: 4, salt_bridges: 1 } },
      { pose_id: 1, score: -8.3, binding_energy: -8.3, rmsd: 1.2, cluster_id: 1, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 2, hydrophobic: 5, salt_bridges: 1 } },
      { pose_id: 2, score: -7.9, binding_energy: -7.9, rmsd: 2.1, cluster_id: 2, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 2, hydrophobic: 4, salt_bridges: 1 } },
      { pose_id: 3, score: -7.5, binding_energy: -7.5, rmsd: 2.8, cluster_id: 2, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 1, hydrophobic: 5, salt_bridges: 1 } },
      { pose_id: 4, score: -7.2, binding_energy: -7.2, rmsd: 3.4, cluster_id: 3, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 1, hydrophobic: 4, salt_bridges: 0 } },
      { pose_id: 5, score: -6.9, binding_energy: -6.9, rmsd: 4.1, cluster_id: 3, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 1, hydrophobic: 3, salt_bridges: 0 } },
    ],
    metrics: {
      mean_score: -7.75,
      std_score: 0.73,
      min_score: -8.7,
      max_score: -6.9,
      num_clusters: 3,
      success_rate: 1.0,
      best_rmsd: 0.0,
      confidence_score: 0.89,
      mean_binding_energy: -7.75,
      predicted_ic50: 2.3,
      drug_likeness_score: 0.82,
    },
    output_directory: "/workspace/predictions/job_001_aspirin_cox2/docking",
    raw_results_path: "/workspace/predictions/job_001_aspirin_cox2/docking/results.pdbqt",
    analysis_plots: {},
    execution_time: 342.5,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  job_002_ibuprofen_cox1: {
    job_id: "job_002_ibuprofen_cox1",
    protein_name: "COX-1 Enzyme",
    ligand_name: "Ibuprofen",
    protein_structure: EXAMPLE_PDB,
    ligand_structure: EXAMPLE_PDB,
    best_pose: {
      pose_id: 0,
      score: -9.2,
      binding_energy: -9.2,
      rmsd: 0.0,
      cluster_id: 1,
      pose_file: EXAMPLE_PDB,
      interactions: { h_bonds: 4, hydrophobic: 5, salt_bridges: 1 },
    },
    poses: [
      { pose_id: 0, score: -9.2, binding_energy: -9.2, rmsd: 0.0, cluster_id: 1, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 4, hydrophobic: 5, salt_bridges: 1 } },
      { pose_id: 1, score: -8.8, binding_energy: -8.8, rmsd: 1.1, cluster_id: 1, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 3, hydrophobic: 5, salt_bridges: 1 } },
      { pose_id: 2, score: -8.4, binding_energy: -8.4, rmsd: 1.9, cluster_id: 2, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 3, hydrophobic: 4, salt_bridges: 1 } },
      { pose_id: 3, score: -8.0, binding_energy: -8.0, rmsd: 2.5, cluster_id: 2, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 2, hydrophobic: 4, salt_bridges: 1 } },
    ],
    metrics: {
      mean_score: -8.6,
      std_score: 0.53,
      min_score: -9.2,
      max_score: -8.0,
      num_clusters: 2,
      success_rate: 1.0,
      best_rmsd: 0.0,
      confidence_score: 0.92,
      mean_binding_energy: -8.6,
      predicted_ic50: 1.5,
      drug_likeness_score: 0.88,
    },
    output_directory: "/workspace/predictions/job_002_ibuprofen_cox1/docking",
    raw_results_path: "/workspace/predictions/job_002_ibuprofen_cox1/docking/results.pdbqt",
    analysis_plots: {},
    execution_time: 289.3,
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  job_006_oseltamivir_neuraminidase: {
    job_id: "job_006_oseltamivir_neuraminidase",
    protein_name: "Influenza Neuraminidase",
    ligand_name: "Oseltamivir (Tamiflu)",
    protein_structure: EXAMPLE_PDB,
    ligand_structure: EXAMPLE_PDB,
    best_pose: {
      pose_id: 0,
      score: -8.9,
      binding_energy: -8.9,
      rmsd: 0.0,
      cluster_id: 1,
      pose_file: EXAMPLE_PDB,
      interactions: { h_bonds: 5, hydrophobic: 3, salt_bridges: 2 },
    },
    poses: [
      { pose_id: 0, score: -8.9, binding_energy: -8.9, rmsd: 0.0, cluster_id: 1, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 5, hydrophobic: 3, salt_bridges: 2 } },
      { pose_id: 1, score: -8.5, binding_energy: -8.5, rmsd: 1.3, cluster_id: 1, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 4, hydrophobic: 3, salt_bridges: 2 } },
      { pose_id: 2, score: -8.1, binding_energy: -8.1, rmsd: 2.2, cluster_id: 2, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 4, hydrophobic: 2, salt_bridges: 1 } },
      { pose_id: 3, score: -7.7, binding_energy: -7.7, rmsd: 3.0, cluster_id: 2, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 3, hydrophobic: 2, salt_bridges: 1 } },
      { pose_id: 4, score: -7.4, binding_energy: -7.4, rmsd: 3.8, cluster_id: 3, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 3, hydrophobic: 2, salt_bridges: 0 } },
      { pose_id: 5, score: -7.0, binding_energy: -7.0, rmsd: 4.5, cluster_id: 3, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 2, hydrophobic: 2, salt_bridges: 0 } },
    ],
    metrics: {
      mean_score: -8.27,
      std_score: 0.71,
      min_score: -8.9,
      max_score: -7.0,
      num_clusters: 3,
      success_rate: 1.0,
      best_rmsd: 0.0,
      confidence_score: 0.91,
      mean_binding_energy: -8.27,
      predicted_ic50: 2.3,
      drug_likeness_score: 0.85,
    },
    output_directory: "/workspace/predictions/job_006_oseltamivir_neuraminidase/docking",
    raw_results_path: "/workspace/predictions/job_006_oseltamivir_neuraminidase/docking/results.pdbqt",
    analysis_plots: {},
    execution_time: 360.2,
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  job_007_gefitinib_egfr: {
    job_id: "job_007_gefitinib_egfr",
    protein_name: "EGFR Kinase",
    ligand_name: "Gefitinib",
    protein_structure: EXAMPLE_PDB,
    ligand_structure: EXAMPLE_PDB,
    best_pose: {
      pose_id: 0,
      score: -9.5,
      binding_energy: -9.5,
      rmsd: 0.0,
      cluster_id: 1,
      pose_file: EXAMPLE_PDB,
      interactions: { h_bonds: 4, hydrophobic: 6, salt_bridges: 0, pi_stack: 1 },
    },
    poses: [
      { pose_id: 0, score: -9.5, binding_energy: -9.5, rmsd: 0.0, cluster_id: 1, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 4, hydrophobic: 6, salt_bridges: 0, pi_stack: 1 } },
      { pose_id: 1, score: -9.0, binding_energy: -9.0, rmsd: 1.4, cluster_id: 1, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 3, hydrophobic: 6, salt_bridges: 0, pi_stack: 1 } },
      { pose_id: 2, score: -8.6, binding_energy: -8.6, rmsd: 2.3, cluster_id: 2, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 3, hydrophobic: 5, salt_bridges: 0, pi_stack: 0 } },
      { pose_id: 3, score: -8.2, binding_energy: -8.2, rmsd: 3.1, cluster_id: 2, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 2, hydrophobic: 5, salt_bridges: 0, pi_stack: 0 } },
    ],
    metrics: {
      mean_score: -8.83,
      std_score: 0.58,
      min_score: -9.5,
      max_score: -8.2,
      num_clusters: 2,
      success_rate: 1.0,
      best_rmsd: 0.0,
      confidence_score: 0.93,
      mean_binding_energy: -8.83,
      predicted_ic50: 0.8,
      drug_likeness_score: 0.91,
    },
    output_directory: "/workspace/predictions/job_007_gefitinib_egfr/docking",
    raw_results_path: "/workspace/predictions/job_007_gefitinib_egfr/docking/results.pdbqt",
    analysis_plots: {},
    execution_time: 320.1,
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  job_008_lisinopril_ace: {
    job_id: "job_008_lisinopril_ace",
    protein_name: "Angiotensin-Converting Enzyme (ACE)",
    ligand_name: "Lisinopril",
    protein_structure: EXAMPLE_PDB,
    ligand_structure: EXAMPLE_PDB,
    best_pose: {
      pose_id: 0,
      score: -9.0,
      binding_energy: -9.0,
      rmsd: 0.0,
      cluster_id: 1,
      pose_file: EXAMPLE_PDB,
      interactions: { h_bonds: 6, hydrophobic: 4, salt_bridges: 2 },
    },
    poses: [
      { pose_id: 0, score: -9.0, binding_energy: -9.0, rmsd: 0.0, cluster_id: 1, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 6, hydrophobic: 4, salt_bridges: 2 } },
      { pose_id: 1, score: -8.5, binding_energy: -8.5, rmsd: 1.5, cluster_id: 1, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 5, hydrophobic: 4, salt_bridges: 2 } },
      { pose_id: 2, score: -8.0, binding_energy: -8.0, rmsd: 2.4, cluster_id: 2, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 4, hydrophobic: 4, salt_bridges: 1 } },
      { pose_id: 3, score: -7.5, binding_energy: -7.5, rmsd: 3.2, cluster_id: 2, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 3, hydrophobic: 4, salt_bridges: 1 } },
    ],
    metrics: {
      mean_score: -8.25,
      std_score: 0.65,
      min_score: -9.0,
      max_score: -7.5,
      num_clusters: 2,
      success_rate: 1.0,
      best_rmsd: 0.0,
      confidence_score: 0.88,
      mean_binding_energy: -8.25,
      predicted_ic50: 1.2,
      drug_likeness_score: 0.86,
    },
    output_directory: "/workspace/predictions/job_008_lisinopril_ace/docking",
    raw_results_path: "/workspace/predictions/job_008_lisinopril_ace/docking/results.pdbqt",
    analysis_plots: {},
    execution_time: 300.3,
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  job_009_metformin_ampk: {
    job_id: "job_009_metformin_ampk",
    protein_name: "AMP-Activated Protein Kinase",
    ligand_name: "Metformin",
    protein_structure: EXAMPLE_PDB,
    ligand_structure: EXAMPLE_PDB,
    best_pose: {
      pose_id: 0,
      score: -9.2,
      binding_energy: -9.2,
      rmsd: 0.0,
      cluster_id: 1,
      pose_file: EXAMPLE_PDB,
      interactions: { h_bonds: 5, hydrophobic: 2, salt_bridges: 2 },
    },
    poses: [
      { pose_id: 0, score: -9.2, binding_energy: -9.2, rmsd: 0.0, cluster_id: 1, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 5, hydrophobic: 2, salt_bridges: 2 } },
      { pose_id: 1, score: -8.8, binding_energy: -8.8, rmsd: 1.6, cluster_id: 1, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 4, hydrophobic: 2, salt_bridges: 2 } },
      { pose_id: 2, score: -8.4, binding_energy: -8.4, rmsd: 2.5, cluster_id: 2, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 4, hydrophobic: 2, salt_bridges: 1 } },
      { pose_id: 3, score: -8.0, binding_energy: -8.0, rmsd: 3.3, cluster_id: 2, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 3, hydrophobic: 2, salt_bridges: 1 } },
    ],
    metrics: {
      mean_score: -8.6,
      std_score: 0.53,
      min_score: -9.2,
      max_score: -8.0,
      num_clusters: 2,
      success_rate: 1.0,
      best_rmsd: 0.0,
      confidence_score: 0.85,
      mean_binding_energy: -8.6,
      predicted_ic50: 1.0,
      drug_likeness_score: 0.84,
    },
    output_directory: "/workspace/predictions/job_009_metformin_ampk/docking",
    raw_results_path: "/workspace/predictions/job_009_metformin_ampk/docking/results.pdbqt",
    analysis_plots: {},
    execution_time: 330.4,
    timestamp: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
  },
  job_010_semaglutide_glp1r: {
    job_id: "job_010_semaglutide_glp1r",
    protein_name: "GLP-1 Receptor",
    ligand_name: "Semaglutide",
    protein_structure: EXAMPLE_PDB,
    ligand_structure: EXAMPLE_PDB,
    best_pose: {
      pose_id: 0,
      score: -9.3,
      binding_energy: -9.3,
      rmsd: 0.0,
      cluster_id: 1,
      pose_file: EXAMPLE_PDB,
      interactions: { h_bonds: 7, hydrophobic: 5, salt_bridges: 2 },
    },
    poses: [
      { pose_id: 0, score: -9.3, binding_energy: -9.3, rmsd: 0.0, cluster_id: 1, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 7, hydrophobic: 5, salt_bridges: 2 } },
      { pose_id: 1, score: -8.9, binding_energy: -8.9, rmsd: 1.7, cluster_id: 1, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 6, hydrophobic: 5, salt_bridges: 2 } },
      { pose_id: 2, score: -8.5, binding_energy: -8.5, rmsd: 2.6, cluster_id: 2, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 5, hydrophobic: 4, salt_bridges: 1 } },
      { pose_id: 3, score: -8.1, binding_energy: -8.1, rmsd: 3.4, cluster_id: 2, pose_file: EXAMPLE_PDB, interactions: { h_bonds: 4, hydrophobic: 4, salt_bridges: 1 } },
    ],
    metrics: {
      mean_score: -8.7,
      std_score: 0.55,
      min_score: -9.3,
      max_score: -8.1,
      num_clusters: 2,
      success_rate: 1.0,
      best_rmsd: 0.0,
      confidence_score: 0.87,
      mean_binding_energy: -8.7,
      predicted_ic50: 0.9,
      drug_likeness_score: 0.89,
    },
    output_directory: "/workspace/predictions/job_010_semaglutide_glp1r/docking",
    raw_results_path: "/workspace/predictions/job_010_semaglutide_glp1r/docking/results.pdbqt",
    analysis_plots: {},
    execution_time: 350.5,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
}

/** Solana-like tx signatures (base58, ~88 chars). Use these in Blockchain verify examples. */
export const mockBlockchainTransactions = [
  {
    signature: "5VERv8NMvzbJMEkV8xnrLkEaWRtSz9CosKDYjCJjBRnbJLgp8uirBgmQpjKhoR4tjF3ZpRzrFmBV6UjKdiSZkQUW",
    jobId: "job_001_aspirin_cox2",
    reportType: "comprehensive",
    stakeholder: "researcher",
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    reportHash: "a7f3e9d2c8b4f1a6e5d3c9b7a2f8e4d1c6b9a5e2f7d3c8b4a1e6f9d2c5b8a3e7f1",
    metadata: {
      proteinName: "COX-2 Enzyme",
      ligandName: "Aspirin",
      bindingScore: -8.7,
      confidence: 0.89,
    },
    blockTime: Math.floor((Date.now() - 1 * 60 * 60 * 1000) / 1000),
    slot: 285678901,
  },
  {
    signature: "4K6Yw8XlJ2O3uV7mP1eQ5sK0rZ6hC8bF3dA2iE7lM5oW1uJ4vS8xT3qD0nH6pK2rL5mN7aU3bY1wS4oP6zJ8kR",
    jobId: "job_002_ibuprofen_cox1",
    reportType: "summary",
    stakeholder: "investor",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    reportHash: "b8e4f0d3c9a5b2f7e6d4c0b8a3f9e5d2c7b0a6f3e8d5c2b9a7f4e1d8c3b6a0f9",
    metadata: {
      proteinName: "COX-1 Enzyme",
      ligandName: "Ibuprofen",
      bindingScore: -9.2,
      confidence: 0.92,
    },
    blockTime: Math.floor((Date.now() - 3 * 60 * 60 * 1000) / 1000),
    slot: 285667812,
  },
  {
    signature: "3L5nM8bV4cZ2xW5tY1pR7aK9E1oI7qH3sL6nM8bV4cZ2xW5tY1pR7aK9E1oI7qH3sL6nM8bV4cZ2xW5",
    jobId: "job_006_oseltamivir_neuraminidase",
    reportType: "comprehensive",
    stakeholder: "researcher",
    timestamp: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    reportHash: "c9d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2",
    metadata: {
      proteinName: "Influenza Neuraminidase",
      ligandName: "Oseltamivir (Tamiflu)",
      bindingScore: -8.9,
      confidence: 0.91,
    },
    blockTime: Math.floor((Date.now() - 7 * 60 * 60 * 1000) / 1000),
    slot: 285656723,
  },
  {
    signature: "2M4oN9cW5dA3yX6uZ2qS8bL0F1pK7aJ4eI3rH9sG5tU1vD6wC2xE8fB4nY0mT7zR3qP6oL9jK2iH5gF8",
    jobId: "job_007_gefitinib_egfr",
    reportType: "summary",
    stakeholder: "investor",
    timestamp: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
    reportHash: "d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1",
    metadata: {
      proteinName: "EGFR Kinase",
      ligandName: "Gefitinib",
      bindingScore: -9.5,
      confidence: 0.93,
    },
    blockTime: Math.floor((Date.now() - 11 * 60 * 60 * 1000) / 1000),
    slot: 285645634,
  },
  {
    signature: "7ZqR2sT4uV6wX8yA0bC1dE3fG5hI7jK9lM1nO3pQ5rS7tU9vW1xY3zA5bC7dE9fG1hI3jK5lM7nO9pQ",
    jobId: "job_010_semaglutide_glp1r",
    reportType: "comprehensive",
    stakeholder: "regulator",
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    reportHash: "e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2",
    metadata: {
      proteinName: "GLP-1 Receptor",
      ligandName: "Semaglutide",
      bindingScore: -9.3,
      confidence: 0.87,
    },
    blockTime: Math.floor((Date.now() - 4 * 60 * 60 * 1000) / 1000),
    slot: 285662445,
  },
]

export const mockAIAnalyses = {
  job_006_oseltamivir_neuraminidase: {
    researcher: {
      summary:
        "Oseltamivir demonstrates strong binding to the active site of influenza neuraminidase with a binding energy of -8.9 kcal/mol. Key interactions include hydrogen bonds with Arg152, Glu119, and Asp151, characteristic of effective neuraminidase inhibitors. The predicted IC50 of 2.3 nM aligns with experimental data.",
      bindingAnalysis: {
        keyResidues: ["Arg152", "Glu119", "Asp151", "Arg371", "Tyr406"],
        hydrophobicInteractions: "Strong hydrophobic pocket formed by Trp178 and Ile222",
        electrostaticContributions: "Significant stabilization from carboxylate-arginine salt bridges",
        solventExposure: "Minimal water-mediated interactions suggest tight binding",
      },
      recommendations: [
        "Explore modifications to the pentyl ether group for improved potency",
        "Investigate resistance mutations at positions 119, 152, and 274",
        "Consider combination therapy with M2 inhibitors for broad-spectrum activity",
      ],
      confidence: 0.91,
    },
    clinician: {
      summary:
        "Oseltamivir (Tamiflu) shows excellent safety profile with oral bioavailability of 80% and rapid conversion to active metabolite. Predicted therapeutic index is favorable with low toxicity risk. Suitable for outpatient treatment of influenza A and B within 48 hours of symptom onset.",
      clinicalApplication: {
        indication: "Treatment and prophylaxis of influenza A and B",
        dosing: "75 mg twice daily for 5 days (treatment), once daily for prevention",
        safetyProfile: "Generally well-tolerated, nausea most common side effect (10-15%)",
        contraindications: "Use with caution in severe renal impairment",
      },
      recommendations: [
        "Initiate treatment within 48 hours of symptom onset for maximum efficacy",
        "Consider prophylactic dosing for high-risk populations during outbreaks",
        "Monitor for emerging resistant strains (H275Y mutation)",
        "Adjust dosing in patients with renal impairment (CrCl < 30 mL/min)",
      ],
      confidence: 0.88,
    },
    investor: {
      summary:
        "Strong commercial potential demonstrated by existing market success ($2.5B annual sales). Computational validation confirms mechanism of action. Low development risk due to established safety profile. Opportunities exist for next-generation derivatives targeting resistant strains.",
      marketOpportunity: {
        marketSize: "$2.5B annual global sales for oseltamivir",
        competitiveLandscape: "Dominant neuraminidase inhibitor, competing with baloxavir",
        developmentStage: "Approved and marketed",
        intellectualProperty: "Original patents expired, generic competition present",
      },
      recommendations: [
        "Invest in next-generation neuraminidase inhibitors targeting H275Y resistance",
        "Explore combination products with baloxavir for synergistic effects",
        "Develop improved formulations (long-acting, inhalable) for patient convenience",
        "Target pandemic preparedness markets and government stockpiling programs",
      ],
      confidence: 0.85,
    },
    regulator: {
      summary:
        "Oseltamivir meets regulatory standards for antiviral efficacy and safety. Computational predictions align with Phase III clinical trial data showing 1-day reduction in symptom duration. Post-market surveillance shows acceptable safety profile with rare neuropsychiatric events.",
      safetyProfile: {
        adverseEvents: "Nausea (10-15%), vomiting (8%), headache (2%)",
        rareEvents: "Neuropsychiatric events (primarily in adolescents, incidence 0.01%)",
        drugInteractions: "Minimal CYP450 interactions, low DDI potential",
        specialPopulations: "Approved for children >1 year, pregnancy category C",
      },
      recommendations: [
        "Continue post-market surveillance for neuropsychiatric adverse events",
        "Monitor resistance patterns through global surveillance networks",
        "Maintain strategic stockpiles for pandemic preparedness",
        "Evaluate real-world effectiveness data annually",
      ],
      confidence: 0.92,
    },
  },
  job_007_gefitinib_egfr: {
    researcher: {
      summary:
        "Gefitinib shows selective binding to EGFR tyrosine kinase domain with binding energy of -9.5 kcal/mol. Quinazoline core forms critical hydrogen bonds with Met793 backbone. Aniline substituent occupies hydrophobic pocket formed by Leu718 and Val726. Higher affinity for activating mutations (L858R, exon 19 deletions) compared to wild-type EGFR.",
      bindingAnalysis: {
        keyResidues: ["Met793", "Lys745", "Leu718", "Val726", "Thr790"],
        hydrophobicInteractions: "Aniline ring stacks with aromatic residues in ATP pocket",
        electrostaticContributions: "H-bond donor-acceptor interactions with hinge region",
        solventExposure: "Morpholine group exposed to solvent, modulates selectivity",
      },
      recommendations: [
        "Design derivatives to overcome T790M gatekeeper mutation resistance",
        "Explore covalent warheads for irreversible inhibition",
        "Investigate dual EGFR/HER2 inhibitors for broader spectrum activity",
        "Optimize linker region for improved brain penetration (CNS metastases)",
      ],
      confidence: 0.93,
    },
    clinician: {
      summary:
        "Gefitinib is first-line therapy for EGFR-mutant non-small cell lung cancer (NSCLC). Oral bioavailability 60%, well-tolerated with manageable side effects. Objective response rate 60-70% in EGFR mutation-positive patients. Median progression-free survival 9-13 months. Resistance typically emerges via T790M mutation.",
      clinicalApplication: {
        indication: "First-line treatment of metastatic NSCLC with EGFR activating mutations",
        dosing: "250 mg once daily, continuous until progression or unacceptable toxicity",
        safetyProfile: "Rash (50%), diarrhea (25%), elevated liver enzymes (10-15%)",
        contraindications: "Severe hepatic impairment, interstitial lung disease",
      },
      recommendations: [
        "Mandatory EGFR mutation testing before initiation (L858R, exon 19 deletions)",
        "Monitor for skin toxicity and treat with topical/systemic therapies",
        "Perform serial LFTs monthly for first 3 months, then quarterly",
        "Switch to osimertinib upon detection of T790M resistance mutation",
      ],
      confidence: 0.89,
    },
    investor: {
      summary:
        "Validated target with $1.5B peak sales for gefitinib. Strong proof-of-concept for targeted cancer therapy. Market expanding with companion diagnostic integration. Next-generation inhibitors (osimertinib) capturing resistance market ($5B opportunity). Combination strategies with immunotherapy show promise.",
      marketOpportunity: {
        marketSize: "$8B global EGFR inhibitor market (growing 7.5% CAGR)",
        competitiveLandscape: "Osimertinib (3rd-gen) now standard, gefitinib/erlotinib competitors",
        developmentStage: "Multiple generics available, original patent expired",
        intellectualProperty: "Opportunities in next-gen inhibitors and combination products",
      },
      recommendations: [
        "Invest in 4th-generation EGFR inhibitors overcoming C797S resistance",
        "Develop EGFR-targeted antibody-drug conjugates for resistant disease",
        "Explore EGFR/MET dual inhibitors for bypass resistance mechanisms",
        "Invest in biomarker-driven patient selection platforms",
      ],
      confidence: 0.87,
    },
    regulator: {
      summary:
        "Gefitinib approved based on Phase III trials demonstrating superior PFS vs chemotherapy in EGFR-mutant NSCLC. Companion diagnostic required for patient selection. Acceptable benefit-risk profile with manageable toxicities. Post-market data confirms clinical trial findings.",
      safetyProfile: {
        adverseEvents: "Rash/acne (50%), diarrhea (25%), dry skin (20%)",
        rareEvents: "Interstitial lung disease (1%), hepatotoxicity (0.5%)",
        drugInteractions: "CYP3A4 substrate, avoid strong CYP3A4 inhibitors/inducers",
        specialPopulations: "Dose reduction in severe renal impairment not required",
      },
      recommendations: [
        "Require EGFR mutation testing as companion diagnostic",
        "Monitor liver function tests during treatment",
        "Include Black Box Warning for interstitial lung disease",
        "Mandate REMS program for severe dermatologic reactions",
      ],
      confidence: 0.91,
    },
  },
  job_001_aspirin_cox2: {
    researcher: {
      summary:
        "Aspirin exhibits irreversible acetylation of Ser530 in the COX-2 active site with a binding energy of -8.7 kcal/mol. The acetyl group transfers to the hydroxyl of Ser530, permanently inactivating the enzyme. Key interactions include hydrogen bonding with Tyr385 and hydrophobic contacts in the narrow channel leading to the catalytic site. The predicted binding mode is consistent with crystallographic data for covalently bound inhibitors.",
      bindingAnalysis: {
        keyResidues: ["Ser530", "Tyr385", "Arg120", "Glu524", "Val349"],
        hydrophobicInteractions: "Phenyl ring occupies hydrophobic side pocket; acetate in narrow channel",
        electrostaticContributions: "Carboxylate forms salt bridge with Arg120; crucial for selectivity",
        solventExposure: "Moderate—acetyl transfer mechanism requires solvent exclusion at active site",
      },
      recommendations: [
        "Explore prodrug strategies to reduce gastric COX-1-mediated side effects",
        "Investigate aspirin–polyphenol combinations for enhanced anti-inflammatory activity",
        "Evaluate low-dose regimens for cardioprotection vs anti-inflammatory dosing",
      ],
      confidence: 0.89,
    },
    clinician: {
      summary:
        "Aspirin remains first-line for cardioprotection (75–100 mg daily) and antiplatelet therapy. Anti-inflammatory dosing (325–650 mg) effective for pain/fever but carries GI bleeding risk. Computational data support irreversible COX-2 inhibition; clinically, COX-1 inhibition drives antiplatelet effect and GI toxicity. Drug–drug interactions with anticoagulants, NSAIDs, and SSRIs require careful management.",
      clinicalApplication: {
        indication: "Cardioprotection, antiplatelet, pain, fever, inflammation",
        dosing: "75–100 mg daily (cardio); 325–650 mg q4–6h PRN (pain); load 162–325 mg (ACS)",
        safetyProfile: "GI bleeding, Reye syndrome (avoid in children with viral illness), bronchospasm in aspirin-sensitive asthma",
        contraindications: "Active bleeding, severe hepatic/renal failure, third-trimester pregnancy",
      },
      recommendations: [
        "Use PPI or misoprostol when combining with anticoagulants or in high GI risk",
        "Avoid in children <16 with viral illness (Reye syndrome)",
        "Consider genotype (CYP2C9, PTGS1) for bleeding risk stratification",
      ],
      confidence: 0.87,
    },
    investor: {
      summary:
        "Aspirin is generic and commoditized; revenue from aspirin itself is minimal. Computational validation supports mechanism but does not create IP. Opportunity lies in novel formulations (e.g., coordinated release, lipid-based), fixed-dose combinations with PPI or statins, and digital adherence tools. Regulatory and payer focus on value-based use (e.g., appropriate vs inappropriate prophylaxis).",
      marketOpportunity: {
        marketSize: "Commodity OTC/ Rx market; combination products and digital adjacencies",
        competitiveLandscape: "Generic dominance; differentiation via formulation and combinations",
        developmentStage: "Mature; lifecycle management and combination development",
        intellectualProperty: "Composition expired; formulation and method patents remain",
      },
      recommendations: [
        "Focus on fixed-dose combinations (aspirin + PPI, aspirin + statin) and adherence tech",
        "Explore aspirin in emerging indications (e.g., cancer prevention) with trial data",
        "Invest in formulations reducing GI toxicity while preserving efficacy",
      ],
      confidence: 0.84,
    },
    regulator: {
      summary:
        "Aspirin is well-established OTC and Rx; computational data align with known mechanism and crystallography. No new regulatory submissions expected for plain aspirin. Post‑market focus on appropriate use, GI and bleeding risk communication, and pediatric restrictions. Combination products and new indications would require standard efficacy/safety data.",
      safetyProfile: {
        adverseEvents: "GI ulceration/bleeding, hypersensitivity, tinnitus at high doses",
        rareEvents: "Reye syndrome, angioedema, thrombocytopenia",
        drugInteractions: "Anticoagulants, NSAIDs, SSRIs, glucocorticoids—increased bleeding risk",
        specialPopulations: "Avoid in third trimester; caution in elderly, renal/hepatic impairment",
      },
      recommendations: [
        "Maintain clear labeling on bleeding risk, GI toxicity, and pediatric Reye avoidance",
        "Monitor post-market data on combinations and off-label use",
        "Ensure OTC labeling supports appropriate self-selection and escalation",
      ],
      confidence: 0.91,
    },
  },
  job_002_ibuprofen_cox1: {
    researcher: {
      summary:
        "Ibuprofen binds reversibly to COX-1 with -9.2 kcal/mol binding energy. The propionic acid group engages Arg120 and Tyr355; the iso-butyl and phenyl substituents occupy hydrophobic pockets. Stereoselectivity: S-enantiomer is active. The binding mode is consistent with other propionic acid NSAIDs; slight differences in substituents drive COX-1 vs COX-2 selectivity and pharmacokinetics.",
      bindingAnalysis: {
        keyResidues: ["Arg120", "Tyr355", "Ser530", "Leu352", "Val349"],
        hydrophobicInteractions: "Iso-butyl and aromatic ring fill hydrophobic channel; determine duration and selectivity",
        electrostaticContributions: "Carboxylate–Arg120 salt bridge; minor H-bonds with Tyr355",
        solventExposure: "Acid group partially solvent-exposed; influences absorption and half-life",
      },
      recommendations: [
        "Compare COX-1 vs COX-2 selectivity with docking of COX-2 structure",
        "Explore prodrugs (e.g., ester, amide) for improved GI tolerance and onset",
        "Investigate enantiopure S-ibuprofen formulations for potency and PK",
      ],
      confidence: 0.92,
    },
    clinician: {
      summary:
        "Ibuprofen is widely used for pain, fever, and inflammation (200–800 mg TID–QID). Onset ~30 min; half-life 2–4 h. COX-1 inhibition confers antiplatelet effect (weaker than aspirin) and GI risk. Caution with CVD; avoid in late pregnancy. Topical and IV formulations available. Computational affinity aligns with reversible, non-selective COX inhibition.",
      clinicalApplication: {
        indication: "Mild–moderate pain, fever, inflammation; juvenile idiopathic arthritis",
        dosing: "200–400 mg q4–6h PRN; max 3.2 g/day (Rx); lower in elderly and renal impairment",
        safetyProfile: "GI discomfort, edema, HTN; rare GI bleed, AKI, hypersensitivity",
        contraindications: "CABG perioperative, late pregnancy, active ulcer, NSAID/aspirin hypersensitivity",
      },
      recommendations: [
        "Use lowest effective dose and shortest duration; add PPI in GI risk",
        "Avoid in CVD patients unless no alternative; do not use for cardioprotection",
        "Consider renal function and drug interactions (anticoagulants, ACEi, diuretics)",
      ],
      confidence: 0.88,
    },
    investor: {
      summary:
        "Ibuprofen is a mature generic NSAID with stable OTC and Rx demand. Computational validation supports mechanism but does not create new IP. Value in extended-release, topical, and combination products (e.g., with paracetamol, caffeine). Growth in OTC self-care and emerging markets; pricing pressure in generics. Differentiated formulations and fixed-dose combinations offer modest upside.",
      marketOpportunity: {
        marketSize: "Large OTC/Rx NSAID segment; ibuprofen among top volume NSAIDs globally",
        competitiveLandscape: "Generic; competition from naproxen, other NSAIDs, and paracetamol",
        developmentStage: "Mature; lifecycle management and OTC line extensions",
        intellectualProperty: "Composition expired; formulation and delivery patents",
      },
      recommendations: [
        "Focus on OTC line extensions, topical/patches, and combination products",
        "Explore emerging markets and digital OTC channels",
        "Consider supply chain and cost advantages for generic ibuprofen",
      ],
      confidence: 0.85,
    },
    regulator: {
      summary:
        "Ibuprofen is long-established OTC and Rx. Computational data align with known reversible COX inhibition. Regulatory focus on appropriate use, GI/CVD risk communication, and pediatric dosing. Combination products and new routes (e.g., IV, topical) require standard dossiers. Post‑market surveillance for GI, renal, and CV events remains relevant.",
      safetyProfile: {
        adverseEvents: "GI upset, nausea, headache, dizziness; elevated BP, edema",
        rareEvents: "GI ulceration/bleeding, AKI, hepatotoxicity, severe skin reactions",
        drugInteractions: "Anticoagulants, ACEi, diuretics, corticosteroids—heightened bleeding/AKI/CV risk",
        specialPopulations: "Avoid in late pregnancy; caution in elderly, renal/hepatic impairment, CVD",
      },
      recommendations: [
        "Maintain clear OTC labeling on dosing, duration, and when to seek care",
        "Monitor CV and GI safety signals in post-market data",
        "Ensure Rx labeling supports appropriate use vs alternatives (e.g., naproxen, COX-2 selective)",
      ],
      confidence: 0.9,
    },
  },
}

export const mockAlphaFoldJobs = [
  {
    job_id: "af_001_insulin_receptor",
    status: "completed" as const,
    job_type: "sequence_to_docking" as const,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    protein_name: "Insulin Receptor Kinase",
    protein_sequence:
      "MGTGGRRGAAAAPLLVAVAALLLGAAGHLYPGEVCPGMDIRNNLTRLHELENCSVIEGHLQILLMFKTRPEDFRDLSFPKLIMITDYLLLFRVYGLESLKDLFPNLTVIRGSRLFFNYALVIFEMVHLKELGLYNLMNITRGSVRIEKNNELCYLATIDWSRILDSVEDNHIVLNKDDNEECGDICPGTAKGKTNCPATVINGQFVERCWTHSHCQKFAGWHGRISCTDNQGGSRTCENKCWSGERSGALHCGASLHNRPGVRCICIPENNATCTPPQNLDTCTTVSHGNKWKCPSCGKFTQRSGLVHRKCPVSVCPPTPPPPTSTEKEPNTCVSLPPGAFLRCGAVHFLPNVTGNPSPSRRASRSLSGTLPLSSYHQRLSSDGSADCLPPSVGSGKGLIPKAGLCQTCPAGTQCSQLHTEQTSCSCSPPEDGEESETGNSKKPLPSMEPSHVPGGGAAPLFTRVLSTPPRPGLQRSNVDKYTQPPQSSSGEDQKHVSSPGPMPVQASLPSSPKPSLPALPSSPPVLTTRPLPQTTPVMHRLQGSRVVPPAPSPPRLPSSPPFSPPAGDAVWFFVFFVLLLFSLFPGPPWLKLLPLLPLLQLLLLQVLLLYLLGILLLLLHGRHRHHHHHHHHHHHHPGICPAKVCRKPQQPGSGKPGLPPPKEKALCECGKFTQRSGLVHQKCPISVCPPDPPPPTSTEPKEPNCVPTPPGSFLRCGAVHFLPNVTGNPSPTRRASRSLSGTLPLSSYHQRLSSDGSADCLPPSVGSGKGLIPKAGLCQTCPAGTQCSQLHTEQTSCSCSPPEDGEESETGNSKKPLPSMEPSHVPGGGAAPLFTRVLSTPPRPGLQRSNVDKYTQPPQSSSGEDQKHVSSPGPMPVQASLPSSPKPSLPALPSSPPVLTTRPLPQTTPVMHRLQGSRVVPPAPSPPRLPSSPPFSPPAGD",
    ligand_name: "Novel GLP-1 Analog",
    disease_target: "Type 2 Diabetes",
    plddt_score: 91.2,
    top_binding_score: -9.4,
    confidence_assessment: "High confidence - AlphaFold pLDDT > 90, strong binding affinity",
    therapeutic_potential: "Excellent candidate for diabetes treatment - strong receptor binding",
  },
  {
    job_id: "af_002_spike_protein",
    status: "completed" as const,
    job_type: "sequence_to_docking" as const,
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    protein_name: "SARS-CoV-2 Spike Protein RBD",
    protein_sequence:
      "NITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPKKST",
    ligand_name: "Neutralizing Antibody Fragment",
    disease_target: "COVID-19",
    plddt_score: 88.7,
    top_binding_score: -11.2,
    confidence_assessment: "High confidence prediction with excellent binding",
    therapeutic_potential: "Strong neutralization potential for COVID-19 variants",
  },
  {
    job_id: "af_003_alzheimers_target",
    status: "running" as const,
    job_type: "sequence_to_docking" as const,
    created_at: new Date(Date.now() - 45 * 60 * 60 * 1000).toISOString(),
    protein_name: "Beta-Secretase 1 (BACE1)",
    protein_sequence:
      "EPPMSFLEELAKQEARLKEEVQQLVETIRTQAEERELQAGQEAEQFIALQGDAELQRLREELQRLAQRLQEEAELLRALQAELEELQARLAELEELRGRLAELRERLEELRQRLAGLEAELEALRGRLAELRERLEELRQRLAEL",
    ligand_name: "Novel Beta-Secretase Inhibitor",
    disease_target: "Alzheimer's Disease",
    progress: 72,
    current_stage: "docking" as const,
    plddt_score: 86.3,
  },
  {
    job_id: "af_004_cancer_kinase",
    status: "predicting_structure" as const,
    job_type: "sequence_to_docking" as const,
    created_at: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
    protein_name: "BRAF V600E Mutant Kinase",
    protein_sequence:
      "MEHIQGAWKTISNNGDTENLYFQGIINDVPKEVEMEIIGEFSYVNGLPHDVRALMECQYLKLEEALQIAKQQQKEDVVPEDQEDEEMFEFEQEDEEPEDVEPEVPQDEEEPPPQDEDEEMFEFEQEDEEPEDVEPEVPQDEEEPPPQDEDEE",
    ligand_name: "Next-Gen BRAF Inhibitor",
    disease_target: "Melanoma",
    progress: 35,
    current_stage: "alphafold_prediction" as const,
  },
]

export const healthTechInsights = [
  {
    category: "Diabetes Research",
    insight: "AlphaFold predictions showing 91% accuracy for insulin receptor structures enable faster drug discovery",
    impact: "high" as const,
    metric: "15× faster than traditional crystallography",
  },
  {
    category: "Cancer Therapeutics",
    insight: "AI-powered screening identified 3 novel EGFR inhibitors with improved selectivity profiles",
    impact: "high" as const,
    metric: "98.3% prediction accuracy",
  },
  {
    category: "Infectious Disease",
    insight: "Rapid structure prediction of viral proteins enables pandemic response within days instead of months",
    impact: "critical" as const,
    metric: "10-day response time",
  },
  {
    category: "Neurodegeneration",
    insight: "ML-predicted blood-brain barrier penetration improving CNS drug development",
    impact: "medium" as const,
    metric: "67% reduction in failed candidates",
  },
  {
    category: "Antimicrobial Resistance",
    insight: "Structure-based design of PBP inhibitors supports next-generation β-lactam alternatives",
    impact: "high" as const,
    metric: "12 novel scaffolds in pipeline",
  },
  {
    category: "Rare Disease",
    insight: "AI-driven target deconvolution and docking accelerate therapies for ultra-rare indications",
    impact: "medium" as const,
    metric: "40% shorter discovery phase",
  },
]

export const therapeuticAreas = [
  {
    name: "Oncology",
    targets: 127,
    compounds: 2845,
    successRate: 23.4,
    topTarget: "EGFR, BRAF, HER2",
  },
  {
    name: "Metabolic Disorders",
    targets: 89,
    compounds: 1932,
    successRate: 31.2,
    topTarget: "GLP-1R, Insulin Receptor",
  },
  {
    name: "Cardiovascular",
    targets: 64,
    compounds: 1456,
    successRate: 28.7,
    topTarget: "ACE, Renin, β1-adrenergic receptor",
  },
  {
    name: "Neurology",
    targets: 53,
    compounds: 987,
    successRate: 18.9,
    topTarget: "BACE1, Tau, α-synuclein",
  },
  {
    name: "Infectious Disease",
    targets: 78,
    compounds: 2341,
    successRate: 35.6,
    topTarget: "Viral proteases, RdRp, Neuraminidase",
  },
]

export const aiAnalysisExamples = [
  {
    role: "Drug Discovery Researcher",
    title: "Structural Biology Analysis",
    compound: "GLP-1 Receptor Agonist",
    analysis:
      "AlphaFold prediction shows excellent confidence (pLDDT 91.2) for the GLP-1 receptor binding domain. The predicted structure reveals a deep binding pocket with key interactions at Arg190 and Glu364. Molecular docking indicates strong binding affinity (-9.4 kcal/mol) with optimal hydrogen bonding patterns. The compound demonstrates favorable ADMET properties with predicted oral bioavailability of 68% and low hepatotoxicity risk. Recommend advancing to in vitro validation with focus on receptor selectivity profiling.",
  },
  {
    role: "Clinical Development Lead",
    title: "Therapeutic Assessment",
    compound: "BRAF V600E Inhibitor",
    analysis:
      "The AI-predicted structure-activity relationship shows promising selectivity for the V600E mutation over wild-type BRAF (12:1 ratio). Blood-brain barrier penetration probability is 23%, suitable for melanoma but limiting CNS applications. Predicted PK parameters indicate twice-daily dosing with minimal CYP450 interactions. Safety profile analysis shows low cardiotoxicity and no hERG liability. Clinical development timeline estimated at 4.2 years with 68% success probability based on similar kinase inhibitors. Recommend IND-enabling studies with focus on resistance mechanisms.",
  },
  {
    role: "Pharmaceutical Executive",
    title: "Portfolio Investment Analysis",
    compound: "Novel Beta-Secretase Inhibitor",
    analysis:
      "Market opportunity analysis for Alzheimer's disease indicates $15B addressable market with 8M patients in key territories. The AlphaFold-guided design approach reduced discovery timeline by 18 months versus traditional methods. Competitive landscape shows 3 active programs in Phase 2/3, with differentiation potential in CNS penetration (BBB score: 0.87) and reduced mechanism-based toxicity. Development costs projected at $280M with 15% probability of regulatory approval. Intellectual property position is strong with composition of matter claims through 2041. Financial modeling suggests peak sales of $2.3B if approved, with acceptable risk-adjusted NPV for portfolio inclusion.",
  },
]

export const allMockJobs = [...mockAlphaFoldJobs, ...mockDockingJobs].sort(
  (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime(),
)

// Helper functions for generating mock data dynamically
export function generateMockDockingResult(
  jobId: string,
  proteinName: string,
  ligandName: string,
  baseScore: number = -8.5,
): any {
  const numPoses = 6
  const poses = Array.from({ length: numPoses }, (_, i) => ({
    pose_id: i,
    score: baseScore + i * 0.4,
    binding_energy: baseScore + i * 0.4,
    rmsd: i * 1.2,
    cluster_id: Math.floor(i / 2) + 1,
    pose_file: EXAMPLE_PDB,
    interactions: {
      h_bonds: Math.max(1, 5 - i),
      hydrophobic: Math.max(2, 6 - i),
      salt_bridges: i < 3 ? 1 : 0,
      pi_stack: i === 0 && baseScore < -9 ? 1 : 0,
    },
  }))

  const bestPose = poses[0]
  const scores = poses.map((p) => p.score)
  const meanScore = scores.reduce((a, b) => a + b, 0) / scores.length
  const stdScore = Math.sqrt(
    scores.reduce((sum, score) => sum + Math.pow(score - meanScore, 2), 0) / scores.length,
  )

  return {
    job_id: jobId,
    protein_name: proteinName,
    ligand_name: ligandName,
    protein_structure: EXAMPLE_PDB,
    ligand_structure: EXAMPLE_PDB,
    best_pose: bestPose,
    poses,
    metrics: {
      mean_score: meanScore,
      std_score: stdScore,
      min_score: Math.min(...scores),
      max_score: Math.max(...scores),
      num_clusters: Math.ceil(numPoses / 2),
      success_rate: 1.0,
      best_rmsd: 0.0,
      confidence_score: Math.max(0.7, Math.min(0.95, 0.85 + (baseScore + 10) / 20)),
      mean_binding_energy: meanScore,
      predicted_ic50: Math.pow(10, baseScore / 1.36) * 1000, // Convert to nM
      drug_likeness_score: Math.max(0.6, Math.min(0.95, 0.75 + (baseScore + 8) / 10)),
    },
    output_directory: `/workspace/predictions/${jobId}/docking`,
    raw_results_path: `/workspace/predictions/${jobId}/docking/results.pdbqt`,
    analysis_plots: {},
    execution_time: 300 + Math.random() * 100,
    timestamp: new Date().toISOString(),
  }
}

export function generateMockJobStatus(
  jobId: string,
  status: "queued" | "running" | "completed" | "failed" | "predicting_structure" | "structure_predicted" | "docking" | "analyzing",
  options: {
    proteinName?: string
    ligandName?: string
    progress?: number
    error?: string
    plddtScore?: number
    proteinSequence?: string
  } = {},
): any {
  const baseStatus: any = {
    job_id: jobId,
    status,
    created_at: new Date(Date.now() - Math.random() * 24 * 60 * 60 * 1000).toISOString(),
  }

  if (options.proteinName) baseStatus.protein_name = options.proteinName
  if (options.ligandName) baseStatus.ligand_name = options.ligandName
  if (options.progress !== undefined) baseStatus.progress = options.progress
  if (options.error) baseStatus.error = options.error
  if (options.plddtScore !== undefined) baseStatus.plddt_score = options.plddtScore
  if (options.proteinSequence) baseStatus.protein_sequence = options.proteinSequence

  if (status === "completed") {
    baseStatus.completed_at = new Date(Date.now() - Math.random() * 2 * 60 * 60 * 1000).toISOString()
  }

  return baseStatus
}

// Fallback helper functions
export function getMockDockingResult(jobId: string): any | null {
  // Check existing mock data first
  if (mockDockingResults[jobId as keyof typeof mockDockingResults]) {
    return mockDockingResults[jobId as keyof typeof mockDockingResults]
  }

  // Try to find matching job info
  const job = mockDockingJobs.find((j) => j.job_id === jobId)
  if (job) {
    return generateMockDockingResult(job.job_id, job.protein_name, job.ligand_name, -8.5)
  }

  // Generate generic mock data
  return generateMockDockingResult(jobId, "Unknown Protein", "Unknown Ligand", -8.0)
}

export function getMockJobStatus(jobId: string): any | null {
  // Check all mock jobs
  const allJobs = [...mockDockingJobs, ...mockAlphaFoldJobs]
  const job = allJobs.find((j) => j.job_id === jobId)
  if (job) {
    return {
      ...job,
      completed_at: job.status === "completed" ? new Date(Date.now() - 1000).toISOString() : undefined,
    }
  }

  // Generate generic status
  return generateMockJobStatus(jobId, "queued")
}

export function getMockAIAnalysis(jobId: string, stakeholderType: string = "researcher"): any | null {
  const analysis = mockAIAnalyses[jobId as keyof typeof mockAIAnalyses]
  if (analysis && analysis[stakeholderType as keyof typeof analysis]) {
    const stakeholderData = analysis[stakeholderType as keyof typeof analysis] as any
    return {
      analysis: {
        summary: stakeholderData.summary,
        detailed_analysis:
          stakeholderData.bindingAnalysis ||
          stakeholderData.marketOpportunity ||
          stakeholderData.safetyProfile ||
          stakeholderData.clinicalApplication ||
          {},
        limitations: [
          "Analysis based on computational predictions only",
          "Experimental validation required",
          "In vivo efficacy not confirmed",
        ],
      },
      recommendations: stakeholderData.recommendations || [],
      confidence: stakeholderData.confidence || 0.85,
      metadata: {
        model: "gpt-4-turbo",
        costEstimate: 0.0234,
        processingTime: 1.5,
      },
    }
  }

  // Generate generic analysis
  return {
    analysis: {
      summary: `AI analysis for ${jobId} indicates promising binding characteristics. Further experimental validation recommended.`,
      detailed_analysis: {},
      limitations: [
        "Analysis based on computational predictions only",
        "Experimental validation required",
        "In vivo efficacy not confirmed",
      ],
    },
    recommendations: [
      "Proceed with in vitro validation",
      "Consider structural modifications for improved binding",
      "Evaluate ADMET properties",
    ],
    confidence: 0.75,
    metadata: {
      model: "gpt-4-turbo",
      costEstimate: 0.02,
      processingTime: 1.2,
    },
  }
}
